### ISSUE TITLE
UNC paths or mapped drives

### ISSUE THREAD

**Issue by reggie-regg** [pearlxcore/PS4-PKG-Tool#22]
I keep my PKG files on a NAS, and I would like to able to add UNC paths to the folder list, but the browser won't let me choose network locations. So I mapped a drive to my NAS's Samba share, but the application crashes when trying to scan that location. Below is the .NET error I get, and I've attached the log file from the application.

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewColumnCollection.get_Item(Int32 index)
   at PS4_PKG_Tool.Form1.bgwOpenPKG_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

[PS4_PKG_Tool_LogFile.txt](https://github.com/pearlxcore/PS4-PKG-Tool/files/5899063/PS4_PKG_Tool_LogFile.txt)

**Comment by reggie-regg** [comment]
So this only seems to be with one particular Samba share on my network, and I think it is due some partial/incomplete PKG files in there. I can scan other network paths without issue, but it would still be nice to be able to browse for UNC paths. Thanks!
