### ISSUE TITLE
v1.5 crashes when interacting with PS4

### ISSUE THREAD

**Issue by dyerseve** [pearlxcore/PS4-PKG-Tool#42]
Get an error trying to do anything with the PS4. Ping works fine, old version works, but sending a file or checking for a base pkg gives an error.

I've set all the fields in the Settings menu, I'm not sure what this error is referring to.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at PS4_Tools.PKG.SceneRelated.Read_PKG(String pkgfile) in C:\Users\pearlxcore\source\repos\PS4 PKG Tool\PS4_Tools\PS4_Tools\Main.cs:line 6444
   at PS4_PKG_Tool.Form1.SendPKG()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

`

**Comment by pearlxcore** [comment]
Can you provide filename of the PKG?
